# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-06 15:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='valor_balance',
            new_name='saldo',
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_respuesta',
            field=models.DateField(default=datetime.datetime(2017, 5, 24, 10, 23, 37, 366312)),
        ),
    ]
