# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-25 12:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visita',
            old_name='cantidad_biomasa',
            new_name='kilogramos_biomasa',
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_entrega',
            field=models.DateField(default=datetime.datetime(2017, 5, 13, 7, 43, 46, 25422)),
        ),
    ]
