# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-25 12:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0002_auto_20170425_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendarvisita',
            name='fecha_agendada',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_entrega',
            field=models.DateField(default=datetime.datetime(2017, 5, 13, 7, 54, 22, 870406)),
        ),
    ]
