# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-07 20:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0002_auto_20170506_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_respuesta',
            field=models.DateField(default=datetime.datetime(2017, 5, 25, 15, 40, 1, 815522)),
        ),
    ]
