# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-22 16:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0002_auto_20170422_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesosolicitud',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloworld.Empleado'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_entrega',
            field=models.DateField(default=datetime.datetime(2017, 5, 10, 11, 32, 7, 287721)),
        ),
    ]
