# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-25 13:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0003_auto_20170425_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_entrega',
            field=models.DateField(default=datetime.datetime(2017, 5, 13, 8, 26, 51, 580257)),
        ),
    ]
