# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-08 12:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0004_auto_20170508_0719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procesosolicitud',
            old_name='agendarVisita',
            new_name='agendar_Visita',
        ),
        migrations.RenameField(
            model_name='procesosolicitud',
            old_name='infoCompleta',
            new_name='informacion_Completa',
        ),
        migrations.RenameField(
            model_name='procesosolicitud',
            old_name='pagoRealizado',
            new_name='pago_Realizado',
        ),
        migrations.RenameField(
            model_name='procesosolicitud',
            old_name='realizaVisita',
            new_name='realiza_Visita',
        ),
        migrations.RemoveField(
            model_name='procesosolicitud',
            name='verificaInfo',
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_respuesta',
            field=models.DateField(default=datetime.datetime(2017, 5, 26, 7, 27, 11, 273157)),
        ),
    ]
