# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-25 16:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0004_auto_20170425_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_entrega',
            field=models.DateField(default=datetime.datetime(2017, 5, 13, 11, 13, 47, 726933)),
        ),
    ]
