# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-22 16:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0006_auto_20170422_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_entrega',
            field=models.DateField(default=datetime.datetime(2017, 5, 10, 11, 40, 53, 777667)),
        ),
    ]
