# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-08 12:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0006_auto_20170508_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informe_tecnico',
            name='informe',
        ),
        migrations.RemoveField(
            model_name='seguimiento',
            name='adjunto',
        ),
        migrations.RemoveField(
            model_name='subir_acta',
            name='acta',
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_respuesta',
            field=models.DateField(default=datetime.datetime(2017, 5, 26, 7, 33, 42, 895629)),
        ),
    ]
