# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-25 17:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0006_auto_20170425_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acta',
            name='approved',
        ),
        migrations.AlterField(
            model_name='acta',
            name='acta',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_entrega',
            field=models.DateField(default=datetime.datetime(2017, 5, 13, 12, 42, 13, 717187)),
        ),
    ]
