# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-08 16:36
from __future__ import unicode_literals

from django.db import migrations

def cargar_usuarios(apps, schema_editor):
    empleado = apps.get_model("helloworld", "Empleado")
    tec = empleado(password="tecprueba", is_superuser= True, username= "pruebadetec", first_name= "prueba", last_name= "apellido", email= "papellido@ambiental.gov.co", is_staff=True, is_active= True)
    tec.save()


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0007_auto_20170508_0733'),
    ]

    operations = [
        migrations.RunPython(cargar_usuarios),
    ]
