# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-25 17:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0008_auto_20170425_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='acta',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.File'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_entrega',
            field=models.DateField(default=datetime.datetime(2017, 5, 13, 12, 45, 46, 501133)),
        ),
    ]
