# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-25 19:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0010_auto_20170425_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_entrega',
            field=models.DateField(default=datetime.datetime(2017, 5, 13, 14, 8, 51, 574000)),
        ),
    ]
