# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-09 13:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewflow', '0005_rename_flowcls'),
        ('helloworld', '0011_auto_20170508_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='ProcesoSeguimiento',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.Process')),
                ('titulo', models.CharField(default='', max_length=250)),
                ('agendarVisita', models.DateField(blank=True, null=True)),
                ('arboles_en_buen_estado', models.BooleanField(default=False)),
                ('tiempo_cumplido', models.BooleanField(default=False)),
                ('notificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helloworld.Notificacion')),
            ],
            options={
                'abstract': False,
            },
            bases=('viewflow.process',),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_respuesta',
            field=models.DateField(default=datetime.datetime(2017, 5, 27, 8, 45, 55, 448691)),
        ),
        migrations.AddField(
            model_name='procesoseguimiento',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helloworld.Solicitud'),
        ),
        migrations.AddField(
            model_name='procesoseguimiento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helloworld.Empleado'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helloworld.Solicitud'),
        ),
    ]
