# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-25 19:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0011_auto_20170425_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesovisita',
            name='text',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_entrega',
            field=models.DateField(default=datetime.datetime(2017, 5, 13, 14, 28, 53, 52703)),
        ),
    ]
