# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-09 14:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0012_auto_20170509_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_respuesta',
            field=models.DateField(default=datetime.datetime(2017, 5, 27, 9, 3, 12, 92905)),
        ),
    ]
