# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-25 19:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('helloworld', '0012_auto_20170425_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_entrega',
            field=models.DateField(default=datetime.datetime(2017, 5, 13, 14, 59, 34, 982052)),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='id_solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloworld.Solicitud'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='respuesta',
            field=filer.fields.file.FilerFileField(null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.File'),
        ),
    ]
