# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-25 20:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0013_auto_20170425_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_entrega',
            field=models.DateField(default=datetime.datetime(2017, 5, 13, 15, 3, 37, 35140)),
        ),
    ]
