# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-25 20:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0014_auto_20170425_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='id_acta',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_entrega',
            field=models.DateField(default=datetime.datetime(2017, 5, 13, 15, 9, 23, 864330)),
        ),
    ]
