# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-27 12:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0018_auto_20170427_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='id_visita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloworld.Visita'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_entrega',
            field=models.DateField(default=datetime.datetime(2017, 5, 15, 7, 54, 1, 770752)),
        ),
    ]
