# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-27 14:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0023_auto_20170427_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procesovisita',
            name='text',
        ),
        migrations.AddField(
            model_name='procesovisita',
            name='titulo',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='procesosolicitud',
            name='titulo',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_respuesta',
            field=models.DateField(default=datetime.datetime(2017, 5, 15, 9, 20, 17, 404558)),
        ),
    ]
