# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-27 15:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0024_auto_20170427_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informe_tecnico',
            name='informe',
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_respuesta',
            field=models.DateField(default=datetime.datetime(2017, 5, 15, 10, 10, 47, 482237)),
        ),
    ]
